web:
  build: .
  command: bundle exec rails s -p 3030 -b '0.0.0.0'
  volumes:
    - .:/rw_layerspec
  ports:
    - '3030:3030'
  links:
    - mongo
  env_file: .env.development
  environment:
    RACK_ENV: development
    RAILS_ENV: development

mongo:
  image: mongo
  container_name: layerspec-mongo
  command: --smallfiles
  ports:
    - '27017'

redis:
  image: redis
