test:
  build: .
  command: test
  volumes:
    - .:/rw_layerspec
  links:
    - mongo

mongo:
  image: mongo
  container_name: layerspec-mongo
  command: --smallfiles
  ports:
    - '27017'

redis:
  image: redis
